### ISSUE TITLE
[Bug Report] console error after login

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere-vue#1479]
## After login has console error
Just after login and open POS terminal is showed a error
#### Steps to reproduce

1. Login
2. Open Point of Sales Form
3. See error

#### Screenshot or Gif（截图或动态图）
![Screenshot_20220128_122533](https://user-images.githubusercontent.com/2333092/151584023-9addb172-4114-499b-877d-c3fb6b64ac30.png)

#### Expected behavior
A clear console without errors

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

#### Additional context
```
TypeError: Cannot read properties of undefined (reading 'value') at VueComponent.templateCustomerData (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/ADempiere/Form/VPOS/BusinessPartner/index.vue?vue&type=script&lang=js&:417:36) at Watcher.get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4489:25) at Watcher.evaluate (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4591:21) at VueComponent.computedGetter [as templateCustomerData] (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4843:17) at VueComponent.get (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/ADempiere/Form/VPOS/BusinessPartner/index.vue?vue&type=script&lang=js&:389:25) at Watcher.get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4489:25) at Watcher.evaluate (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4591:21) at VueComponent.computedGetter [as displayedValue] (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4843:17) at Object.get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2080:20) at Proxy.render (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"3f9946e5-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/ADempiere/Form/VPOS/BusinessPartner/index.vue?vue&type=template&id=fcb96f6c&:538:24)
```

**Comment by elsiosanchez** [comment]
Greetings, this problem is solved in the next PR #1481
