### ISSUE TITLE
[Bug Report] Process Activity is not showed

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere-vue#1548]
## Bug report
Process activity is not showed after run a process with class not found error

#### Steps to reproduce

1. Open ADempiere
2. Run any process
3. Press notification
4. See the error

#### Screenshot or Gif（截图或动态图）
![Screenshot_20220209_183917](https://user-images.githubusercontent.com/2333092/153302708-4a9c6e7d-4be1-4fdc-9528-de2e95c297f4.png)

#### Other relevant information
- Your OS: Chrome
- Web Browser: 98.0.4758.80 (Official Build) (64-bit)
- Node.js version: latest
- adempiere-vue version: latest develop

#### Additional context
```
error-log.js?b1fc:32 TypeError: Cannot read properties of undefined (reading 'processUuid')
    at eval (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib/index.js!./node_modules/eslint-loader/index.js?!./src/views/ADempiere/ProcessActivity/processActivity.js?vue&type=script&lang=js&:62:55)
    at Array.forEach (<anonymous>)
    at VueComponent.eval (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib/index.js!./node_modules/eslint-loader/index.js?!./src/views/ADempiere/ProcessActivity/processActivity.js?vue&type=script&lang=js&:60:18)
    at Watcher.get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4489:25)
    at Watcher.evaluate (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4591:21)
    at RefImpl.computedGetter [as value] (webpack-internal:///./node_modules/@vue/composition-api/dist/vue-composition-api.esm.js:1505:27)
    at VueComponent.eval (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib/index.js!./node_modules/eslint-loader/index.js?!./src/views/ADempiere/ProcessActivity/processActivity.js?vue&type=script&lang=js&:91:31)
    at Watcher.get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4489:25)
    at Watcher.evaluate (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4591:21)
    at RefImpl.computedGetter [as value] (webpack-internal:///./node_modules/@vue/composition-api/dist/vue-composition-api.esm.js:1505:27) 'render'
eval @ error-log.js?b1fc:32
processLog.js?3c53:106 Error getting process activity: rootGetters.getProcess is not a function. Code: undefined.
```

**Comment by elsiosanchez** [comment]
This problem was fixed in the following PR https://github.com/adempiere/adempiere-vue/pull/1566 waiting for mixing
